# Este arquivo define as versões e as dependências do projeto
[versions]
guava = "33.2.1-jre"
junit = "5.10.3"

[libraries]
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }